language: go

go:
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - master

before_script:
  - curl -sfL https://raw.githubusercontent.com/knqyf263/cob/master/install.sh | sudo sh -s -- -b /usr/local/bin

script:
  - go test -v
  - cob
